Algoritmo "iguais ou diferentes"

Var
	num1, num2 : real

Inicio
	Escreval("Digite um número")
	Leia(num1)
	Escreval("Digite outro número")
	Leia(num2)
	Se (num1=num2) entao
	Escreval("O primeiro número é igual ao segundo")
	Senao
	Se (num1<>num2) entao
	Escreval("Os Números digitados são diferentes")
	se (num1>num2) entao
	escreval("O primeiro número digitado é maior que o segundo")
	senao
   escreval("O segundo número é maior do que o primeiro")
	fimse
	fimse
	fimse
fimalgoritmo


