Algoritmo "qual o maior numero"

Var
	n1, n2, n3 : inteiro

Inicio
	Escreval("Digite um Número")
	Leia(n1)
	Escreval("Digite o Segundo Número")
	Leia(n2)
	Escreval("Digite o Terceiro Número")
	Leia(n3)
	Se n1 > n2 entao
	escreval("O seu primeiro número é o maior entre os três")
	senao
	se n2 > n3 entao
	escreval("O seu segundo número é o maior entre os três")
	senao
	se n3 > n2 entao
	escreval ("O seu terceiro número é o maior entre os três")
	fimse
	fimse
	fimse
fimalgoritmo
