Algoritmo "a media das medias"
Var
m1, m2, mediasoma, mediam : real

Inicio
escreval("A média Aritmética dos números 8, 9 e 7 é igual a: 24/3 = 8")
m1 <- (8)
escreval("A Média Aritmética dos Números 4, 5 e 6 é igual a: 15/3 = 5")
 m2 <- (5)
 mediasoma <- (m1+m2)
 escreval("A Soma das Duas Médias é Igual à: ",mediasoma)
 mediam <- (m1+m2)/2
 escreval("A Média das Médias é igual a: ",mediam)
fimalgoritmo
